sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shubham/frontend-docker -f Dockerfile.dev .

script:
  - docker run shubham/frontend-docker CI=true npm run test -- --coverage